version: '2.2'
volumes:
  swg-default-one:
  swg-default-two:
  swg-default-three:
  swg-blue-one:
  swg-blue-two:
  swg-blue-three:
services:
  consul:
    image: consul:0.9.3
    command:
      - agent
      - -dev
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -ui
      - -log-level=info
    ports:
      - "8500:8500"
    restart: always
  auth:
    extends:
      file: ./docker-compose/common.yml
      service: ros_common
    ports:
      - "9080:9080"
    command:
      - run
      - auth
      - --loglevel=all
      - --advertise-address
      - eth0
    environment:
      LOG_RECV_PORT: 15000
  swg_default_one:
    extends:
      file: ./docker-compose/common.yml
      service: ros_resync
    environment:
      SYNC_ID: one
      SYNC_LABEL: default
    volumes:
      - swg-default-one:/data
  swg_default_two:
    extends:
      file: ./docker-compose/common.yml
      service: ros_resync
    environment:
      SYNC_ID: two
      SYNC_LABEL: default
    volumes:
      - swg-default-two:/data
  swg_default_three:
    extends:
      file: ./docker-compose/common.yml
      service: ros_resync
    volumes:
      - swg-default-three:/data
    environment:
      SYNC_ID: three
      SYNC_LABEL: default
  swg_blue_one:
    extends:
      file: ./docker-compose/common.yml
      service: ros_resync
    environment:
      SYNC_ID: one
      SYNC_LABEL: blue
    volumes:
      - swg-blue-one:/data
  swg_blue_two:
    extends:
      file: ./docker-compose/common.yml
      service: ros_resync
    environment:
      SYNC_ID: two
      SYNC_LABEL: blue
    volumes:
      - swg-blue-two:/data
  swg_blue_three:
    extends:
      file: ./docker-compose/common.yml
      service: ros_resync
    volumes:
      - swg-blue-three:/data
    environment:
      SYNC_ID: three
      SYNC_LABEL: blue
